call Conceal('\<false\>','⊥')
call Conceal('\<const\>','ℂ')
call Conceal('\<let\>','ℓ')
call Conceal('\<function\>','ƒ')
call Conceal('\<new\>','⋆')
call Conceal('\<null\>','⌀')
call Conceal('\<return\>','⎋')
call Conceal('\<this\>','◊')
call Conceal('\<throw\>','⌧')
call Conceal('\<true\>','⊤')
call Conceal('\<with\>\ze(','∪')
call Conceal('\<if\>','☑')
call Conceal('\<else\>','☒')
call Conceal('else\ze if','▣')
call Conceal('else\zs if','')
